DROP TABLE IF EXISTS TEAM;

CREATE TABLE TEAM (name VARCHAR(255) PRIMARY KEY,
city VARCHAR(255) DEFAULT NULL,
owner VARCHAR(255) DEFAULT NULL,
stadium_capacity INT DEFAULT NULL,
tier VARCHAR(255) DEFAULT NULL,
competition VARCHAR(255) DEFAULT NULL,
player_number INT DEFAULT NULL,
creation_date DATE DEFAULT NULL
);